{
  "Char": "Bc",
  "SprAn": "Bc_SprAn.spran",
  "RenderMode": "Sprite",
  "CostumeCount": 1,
  "Sprites": [
    "Bc_Spr.dpspr"
  ],
  "Effects": "Bc_Eff00.prman",
  "PalCount": 1,
  "Palettes": [
    {
      "ColorsInPal": 3,
      "Pals": [
        "Palettes/Color00/YuPal.png",
        "Palettes/Color00/IzPal.png",
        "Palettes/Color00/ZioPal.png"
      ]
    }
  ],
  "StateLists": [
    "Bc_States00.json"
  ],
  "Scripts": [
    "Bc_Script00.lua"
  ]
}